<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="/style.css" />
    <title>The Modern Javascript Bootcamp</title>
  </head>
  <body>
    <div class="doc">
      <nav class="menu"></nav>

      <h1>Classes</h1>
      <nav class="nav"></nav>
      <h2>JS promise</h2>
      <nav class="obj-nav"></nav>
      <!-- start -->
      <h2>Success and Failure Callback Functions</h2>

      <p>
        To handle a “successful” promise, or a promise that resolved, we invoke .then() on the promise, passing in a success handler callback function:
    </p> <p class="code">
        const prom = new Promise((resolve, reject) => {<br>
          resolve('Yay!');<br>
        });<br><br>
         
        const handleSuccess = (resolvedValue) => {<br>
          console.log(resolvedValue);<br>
        };<br><br>
         
        prom.then(handleSuccess); // Prints: 'Yay!'
        </p>

        <p>
        Let’s break down what’s happening in the example code:
        </p><ul>
 <li>         prom is a promise which will resolve to 'Yay!'.</li>  
  <li>        We define a function, handleSuccess(), which prints the argument passed to it.</li>  
   <li>      We invoke prom‘s .then() function passing in our handleSuccess() function.</li>   
  <li>         Since prom resolves, handleSuccess() is invoked with prom‘s resolved value, 'Yay', so 'Yay' is logged to the console.</li> 
        </ul>
      <p>With typical promise consumption, we won’t know whether a promise will resolve or reject, so we’ll need to provide the logic for either case. We can pass both a success callback and a failure callback to .then().</p>  
      <p class="code">
        let prom = new Promise((resolve, reject) => {<br>
          let num = Math.random();<br>
          if (num < .5 ){<br>
            resolve('Yay!');<br>
          } else {<br>
            reject('Ohhh noooo!');<br>
          }<br>
        });<br><br>
         
        const handleSuccess = (resolvedValue) => {<br>
          console.log(resolvedValue);<br>
        };<br><br>
         
        const handleFailure = (rejectionReason) => {<br>
          console.log(rejectionReason);<br>
        };<br><br>
         
        prom.then(handleSuccess, handleFailure);
        </p>
    <p>  Let’s break down what’s happening in the example code:</p>  
    <ul>  
    <li>       prom is a promise which will randomly either resolve with 'Yay!' or reject with 'Ohhh noooo!'.</li> 
    <li>      We pass two handler functions to .then(). The first will be invoked with 'Yay!' if the promise resolves, and the second will be invoked with 'Ohhh noooo!' if the promise rejects.</li>  
    </ul>      
      <p class="tip">     Note: The success callback is sometimes called the “success handler function” or the onFulfilled function. The failure callback is sometimes called the “failure handler function” or the onRejected function. 
         
      </p>

      <h2>Code Example</h2>
      <p class="code">const {checkInventory} = require('./library.js'); <br /> <br />

        const order = [['sunglasses', 1], ['bags', 2]]; <br /> <br />
        
        // Write your code below: <br />
        const handleSuccess = (resolved) => { <br />
          &nbsp;  console.log(resolved) <br />
        } <br />
        
        const handleFailure = (fail) => { <br />
          &nbsp; console.log(fail) <br />
        } <br />
        
        checkInventory(order).then(handleSuccess, handleFailure)</p> <br />

        <p>The code above refernces the code below - this code was held in a seperate file: library.js</p>

        <p class="code">const inventory = {<br />
          sunglasses: 1900,<br />
          pants: 1088,<br />
          bags: 1344<br />
        };<br /><br />
        
        const checkInventory = (order) => {<br />
          return new Promise((resolve, reject) => {<br />
            setTimeout(() => {<br />
              &nbsp;  let inStock = order.every(item => inventory[item[0]] >= item[1]);<br />
              if (inStock) {<br />
                &nbsp;    resolve(`Thank you. Your order was successful.`);<br />
              } else {<br />
                &nbsp;    reject(`We're sorry. Your order could not be completed because some items are sold out.`);<br />
              }<br />
            }, 1000);<br />
            &nbsp; })<br />
        };<br /><br />
        
        module.exports = { checkInventory };</p>

      <!-- &nbsp;  <br /> -->
      <!-- content ends here -->
    </div>
  </body>
  <script src="/menu.js"></script>
  <script src="/prom-nav.js"></script>
  <script src="/nav.js"></script>
</html>
